"""SEARCHING stage: query academic sources for candidate papers."""

from workflow_engine import WorkflowStore
from workflow_models import TaskDefinition, SearchQuery
from pipeline.contracts import SearchProvider


async def run_search_stage(
    job: dict,
    store: WorkflowStore,
    search: SearchProvider,
) -> dict:
    """Execute the SEARCHING pipeline stage.

    Queries the configured SearchProvider for papers matching the task
    definition, then submits the results as candidates.
    """
    task = store.get_task(job["task_id"], job.get("owner_id", "worker"))
    definition = TaskDefinition(**task["definition"])

    query = SearchQuery(
        text=task["query"],
        languages=definition.languages,
    )
    results = await search.search(query)

    # Submit as candidates; store transitions to WAITING_PAPER_APPROVAL
    papers = []
    for r in results:
        papers.append({
            "id": None,  # auto-generated by store
            "work_id": r.work_id,
            "title": r.title,
            "authors": r.authors,
            "year": r.year,
            "abstract": r.abstract,
            "doi": r.doi,
            "source": r.source,
            "document_type": r.document_type,
            "url": r.url,
            "language": r.language,
            "role_tags": [],
            "relevance_score": None,
            "evidence_level": "abstract_only" if not r.abstract else "abstract_only",
            "fulltext_status": "unknown",
        })

    store.submit_candidates(job["task_id"], "worker", papers)
    return {"papers_found": len(papers)}
